# (Optionnel) déclenchement automatique
triggers:
  - event: push
    branch: main
    workflow: ios-only

workflows:
  ios-only:
    name: Build iOS only
    max_build_duration: 60

    # ──────────────
    # Environnement
    # ──────────────
    environment:
      flutter: stable

    # ──────────────
    # Scripts (mêmes 2 espaces d'indent que `environment`)
    # ──────────────
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Update CocoaPods repos
        script: |
          cd ios
          pod repo update
          pod install --repo-update
          cd ..

      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign

    # ──────────────
    # Artifacts
    # ──────────────
    artifacts:
      - build/ios/ipa/*.ipa

    # ──────────────
    # Publication App Store Connect
    # ──────────────
    publishing:
      app_store_connect:
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        key_id:    $APP_STORE_CONNECT_KEY_ID
        api_key:   $APP_STORE_CONNECT_PRIVATE_KEY
