# 1) Triggers au niveau racine : associez l’événement + la branche + le workflow
triggers:
  - event: push
    branch: main
    workflow: flutter-workflow

workflows:
  flutter-workflow:
    name: Build Android & iOS
    max_build_duration: 60

    environment:
      flutter: stable

    # 2) Plus de "triggers" ici

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Build Android APK
        script: |
          flutter build apk --release

      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        key_id:    $APP_STORE_CONNECT_KEY_ID
        api_key:   $APP_STORE_CONNECT_PRIVATE_KEY
        # ipa_path supprimé
