workflows:
  flutter-workflow:
    name: Build Android & iOS
    max_build_duration: 60

    environment:
      flutter: stable

    # déclencheur automatique sur chaque push
    triggers:
      - event: push
        branch: main

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Build Android APK
        script: |
          flutter build apk --release

      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/*.ipa

    publishing:
      # si vous avez configuré App Store Connect API
      app_store_connect:
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        key_id: $APP_STORE_CONNECT_KEY_ID
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        ipa_path: build/ios/ipa/*.ipa
