workflows:
  ios-only:
    name: Build iOS only
    max_build_duration: 60

    environment:
      flutter: stable

    # plus de step Android
      scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Update CocoaPods repos
        script: |
          cd ios
          pod repo update
          pod install --repo-update
          cd ..

      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        key_id:    $APP_STORE_CONNECT_KEY_ID
        api_key:   $APP_STORE_CONNECT_PRIVATE_KEY
