name: faris
description: Application de gestion personnalisée des tontines
publish_to: 'none' # Empêche la publication sur pub.dev

version: 3.3.4+35

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Image picker (nécessaire pour vos imports)
  image_picker: ^1.1.2

  # UI & utilitaires
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  platform: ^3.1.5
  get: ^4.6.6
  get_storage: ^2.0.3
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  cached_network_image: ^3.4.1
  introduction_screen: ^3.0.2
  dotted_border: ^2.1.0
  another_flushbar: ^1.12.30
  jiffy: 6.3.1
  shared_preferences: ^2.3.2
  file_picker: any
  mime_type: any
  http_parser: any

  # Partage
  share_plus: ^10.0.2

  # Cartes & géolocalisation
  google_maps_flutter: ^2.5.0
  geolocator: ^9.0.2
  geocoding: ^2.0.4

  # Téléphone & USSD
  flutter_phone_direct_caller: ^2.1.1
  intl_phone_field: ^3.1.0

  # HTTP
  http: ^1.2.2

  # État & routage
  provider: ^6.0.1

  # Notifications & Firebase
  flutter_local_notifications: ^17.2.3
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  firebase_messaging: ^15.1.6
  firebase_analytics: ^11.3.6
  firebase_remote_config: ^5.3.0

  # Vérification de version
  new_version_plus: ^0.0.12

  # Divers UI
  flutter_svg: ^2.0.10+1
  bottom_navy_bar: ^6.1.0
  flutter_image_stack: ^0.0.6
  lottie: ^1.3.0
  clipboard: ^0.1.3
  equatable: ^2.0.3
  path_provider: ^2.1.4
  pin_code_fields: ^8.0.1
  flutter_widget_from_html_core: ^0.15.2
  url_launcher: ^6.3.0
  flutter_svg_provider: ^1.0.3
  app_settings: ^5.1.1
  fl_chart: ^0.69.0
  badges: ^3.0.2
  animated_bottom_navigation_bar: ^1.3.3
  connectivity_plus: ^6.1.1
  fluttertoast: ^8.0.8
  whatsapp_unilink: ^2.1.0
  auto_size_text: ^3.0.0
  flutter_inappwebview: ^6.0.0+beta.18
  video_player: ^2.7.0
  google_mobile_ads: ^2.1.0
  flutter_foreground_task: ^6.1.2
  location: ^5.0.3

dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  workmanager: ^0.5.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/images/indiv_icon.png
    - assets/images/collective_icon.png
    - assets/images/mes_epargnes.png
    - assets/images/epargnes_partagees.png
    - assets/images/internet.png
    - assets/images/mobile_money.png
    - assets/images/savings.png
    - assets/images/payment.png
    - assets/images/delivery.png
    - assets/images/shopping.png
    - assets/images/orange_money.png
    - assets/images/moov_money.png
    - assets/images/telecel.png
    - assets/images/sank_money.png
    - assets/images/banner_image.png
    - assets/icons/souscrire.png
    - assets/icons/liste_achats.png
    - assets/icons/explorer.png
    - assets/icons/proposition.png
    - assets/images/as_delivery.png
    - assets/images/find_delivery.png
    - assets/icons/no_image.png
    - assets/images/default_avatar.png
    - assets/images/collaboration.png
    - assets/images/logo_all.png
    - assets/images/note_rider.png
    - assets/images/annotated_visa_front.png
    - assets/images/annotated_visa_back.png
    - assets/images/mes_demandes_courses.png
    - assets/images/avail_delivery.png
    - assets/images/search_animation.gif
    - assets/images/map_icon_square.png
    - assets/images/loading.gif
